In [ ]:
import tensorflow as tf

In [ ]:
scaler=tf.constant(133)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=133>

In [ ]:
scaler.ndim

0

In [ ]:
vector=tf.constant([10,5,18])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10,  5, 18], dtype=int32)>

In [ ]:
matrix=tf.constant([[10,5,18],[10,5,18]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10,  5, 18],
       [10,  5, 18]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
matrix=tf.constant([[10.,5.,18.],[10.,5.,18.]],dtype=tf.float16)
matrix

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[10.,  5., 18.],
       [10.,  5., 18.]], dtype=float16)>

In [ ]:
matrix=tf.constant([[10,5,18],[10,5,18]],dtype=tf.float16)
matrix

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[10.,  5., 18.],
       [10.,  5., 18.]], dtype=float16)>

In [ ]:
#Create a 3D tensor
tensor=tf.constant([[[1,2,3],[4,5,6]],
                [[7,8,9],[10,11,12]],
                  [[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
#Creating variable tensor in tensorflow
variable_tensor=tf.Variable([10,7,34])
variable_tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([10,  7, 34], dtype=int32)>

In [ ]:
#constant vector
constant_tensor=tf.constant([10,7,34])
constant_tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10,  7, 34], dtype=int32)>

In [ ]:

variable_tensor[0].assign(17)
variable_tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([17,  7, 34], dtype=int32)>

In [ ]:
constant_tensor[0].assign(17)
#variable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [ ]:
var_matrix=tf.Variable([[1,2,3],[4,5,6]])
var_matrix

In [ ]:
var_matrix[1,1].assign(17)
var_matrix

In [ ]:
import numpy as np

In [ ]:
scaler=10
vector=[12,23,5,53]
array=np.array([[1,2,3],[4,5,6]])
matrix=np.array([[43,45,67],[54,4,54],[233,24,3432]])


In [ ]:
scaler=tf.convert_to_tensor(scaler)
scaler

In [ ]:
vector=tf.convert_to_tensor(vector)
vector

In [ ]:
matrix=tf.convert_to_tensor(matrix)
matrix

In [ ]:
#Creating random tensors
#1. using Normal(Gaussian) Distribution

tensor = tf.random.normal(shape=(3,2),mean=10.0,stddev=2.0,dtype=tf.float16)
tensor



In [ ]:
#Creating random tensors
#1. Using Uniform Distribution

tensor = tf.random.uniform(shape=(3,2),minval=1.0,maxval=5.0,dtype=tf.float16)
tensor

# How to get a Basic information from a tensor
1. Data Type of a Tensor
2. Shape of a tensor
3. Rank or number of dimensions of a tensor
4. Total number of elements in a tensor

In [ ]:
#3D Tensor using constant
tensor_3d= tf.constant([[[1,2,3,],[4,6,7]],
                     [[45,65,7],[67,786,2]],
                     [[423,536,75],[948,39,120]]])

tensor_3d

In [ ]:

print("Data type of a tensor",tensor_3d.dtype)

In [ ]:
print("Shape of a tensor",tensor_3d.shape)

In [ ]:
print("Rank or number of dimensions of a tensor:",tensor_3d.ndim)

In [ ]:
#Total number of elements in a tensor(Count)
print("Total number of elements in a tensor ", tf.size(tensor_3d))

In [ ]:


#Total number of elements in a tensor(Fetch the Value)
print("Total number of elements in a tensor ", tf.size(tensor_3d).numpy())

In [ ]:

tensor_3d.numpy()

# Indexing and Slicing With Tensor

In [ ]:

vector=tf.constant([10,5,18,32,4,7,85,32,54,65,76,2,12])
vector

In [ ]:





vector[0]

In [ ]:






vector[7]

In [ ]:

vector[:]

In [ ]:
vector[1:5]

In [ ]:






vector[::-1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([18,  5, 10], dtype=int32)>

In [ ]:

#Fetch multiple elements from a tensor for multiple indices: tf.gather()
indices=tf.constant([2,5])
tf.gather(vector,indices)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([18,  7], dtype=int32)>

In [ ]:
#Indexing on matrix tensor
matrix=tf.constant([[10,5,18],[1,15,8],[5,9,77]])
matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10,  5, 18],
       [ 1, 15,  8],
       [ 5,  9, 77]], dtype=int32)>

In [ ]:
# For getting element at 0th row and 1st column
matrix[0,1]

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [ ]:
matrix[0,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10,  5, 18], dtype=int32)>

In [ ]:
matrix[:2,:]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10,  5, 18],
       [ 1, 15,  8]], dtype=int32)>

In [ ]:
matrix[:,:2]

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  5],
       [ 1, 15],
       [ 5,  9]], dtype=int32)>

#Create a tensor with a sequence of numbers using tf.range()

Syntax:

tf.range(start,limit,delta=1,dtype=None,name='range')

In [ ]:
vec_tensor=tf.range(start=1,limit=10,delta=2,dtype=tf.int32)
vec_tensor

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9], dtype=int32)>

In [ ]:
limit=10
tf.range(limit)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
even_tensor=tf.range(start=2,limit=21,delta=2)
even_tensor

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20], dtype=int32)>

In [ ]:
odd_tensor=tf.range(start=1,limit=21,delta=2)
odd_tensor

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19], dtype=int32)>

In [ ]:
reverse_tensor=tf.range(start=20,limit=1,delta=-2)
reverse_tensor

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2], dtype=int32)>

# Typecasting of Tensor


In [ ]:
tensor_float=tf.constant([10.4,11.2,76.8,19.65])
tensor_float,tensor_float.dtype

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([10.4 , 11.2 , 76.8 , 19.65], dtype=float32)>,
 tf.float32)

In [ ]:
tensor_int=tf.constant([21,76,88])
tensor_int,tensor_int.dtype

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([21, 76, 88], dtype=int32)>,
 tf.int32)

In [ ]:
tensor_float_to_int=tf.cast(tensor_float,dtype=tf.int32)
tensor_float_to_int,tensor_float_to_int.dtype

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10, 11, 76, 19], dtype=int32)>,
 tf.int32)

In [ ]:
tf.cast(tensor_int,dtype=tf.float32)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([21., 76., 88.], dtype=float32)>

In [ ]:
tf.cast(tensor_float,dtype=tf.int32)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10, 11, 76, 19], dtype=int32)>

In [ ]:
tf.cast(tensor_float,dtype=tf.float16)

<tf.Tensor: shape=(4,), dtype=float16, numpy=array([10.4 , 11.2 , 76.8 , 19.66], dtype=float16)>

In [ ]:
tf.constant(["x","y","z"])

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'x', b'y', b'z'], dtype=object)>

# Basic Math Operations on Tensors

In [ ]:
x=tf.constant([10.0,20.0,30.0,54.0])
y=tf.constant([1.,2.,3.,4.])

x,y

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([10., 20., 30., 54.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>)

In [ ]:
x+10

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([20., 30., 40., 64.], dtype=float32)>

In [ ]:
x+y

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([11., 22., 33., 58.], dtype=float32)>

In [ ]:
#inbuilt ADD method
add=tf.add(x,y)
add

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([11., 22., 33., 58.], dtype=float32)>

In [ ]:
x-10

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 0., 10., 20., 44.], dtype=float32)>

In [ ]:
x-y

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 9., 18., 27., 50.], dtype=float32)>

In [ ]:
#inbuilt subtract method
subtract=tf.subtract(x,y)
subtract

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 9., 18., 27., 50.], dtype=float32)>

In [ ]:
# Multiplication
x*10

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([100., 200., 300., 540.], dtype=float32)>

In [ ]:
x*y

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 10.,  40.,  90., 216.], dtype=float32)>

In [ ]:
mul=tf.multiply(x,y)
mul

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 10.,  40.,  90., 216.], dtype=float32)>

In [ ]:
#Division
x/10

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1. , 2. , 3. , 5.4], dtype=float32)>

In [ ]:
x/y

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([10. , 10. , 10. , 13.5], dtype=float32)>

In [ ]:
div=tf.divide(x,y)
div

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([10. , 10. , 10. , 13.5], dtype=float32)>

In [ ]:
#Square of tensor
x*x

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 100.,  400.,  900., 2916.], dtype=float32)>

In [ ]:
square=tf.square(x)
square

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 100.,  400.,  900., 2916.], dtype=float32)>

In [ ]:
#power
power=tf.pow(x,3)
power


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([  1000.,   8000.,  27000., 157464.], dtype=float32)>

In [ ]:
x**3

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([  1000.,   8000.,  27000., 157464.], dtype=float32)>

In [ ]:
#Squared_difference between 2 tensors
sq_diff=tf.math.squared_difference(x,y)
sq_diff

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([  81.,  324.,  729., 2500.], dtype=float32)>

In [ ]:
(x-y)**2

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([  81.,  324.,  729., 2500.], dtype=float32)>

In [ ]:
tensor=tf.constant([98,40,32,22,12,39])
tensor

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([98, 40, 32, 22, 12, 39], dtype=int32)>

In [ ]:
#index of the min and max element of a tensor
min_element_index=tf.argmin(tensor)
max_element_index=tf.argmax(tensor)
min_element_index,max_element_index

(<tf.Tensor: shape=(), dtype=int64, numpy=4>,
 <tf.Tensor: shape=(), dtype=int64, numpy=0>)

In [ ]:
#value of min and max element of a tensor
min=tf.reduce_min(tensor)
max=tf.reduce_max(tensor)
min,max

(<tf.Tensor: shape=(), dtype=int32, numpy=12>,
 <tf.Tensor: shape=(), dtype=int32, numpy=98>)

In [ ]:
mat=tf.constant([[15,20,13],[84,45,36]])
mat

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[15, 20, 13],
       [84, 45, 36]], dtype=int32)>

In [ ]:
#Find sum of a tensor
sum=tf.reduce_sum(mat)
sum

<tf.Tensor: shape=(), dtype=int32, numpy=213>

In [ ]:
#Find the sum along the axis

#Find the sum  row-wise
sum_0=tf.reduce_sum(mat,axis=0)
#Find the sum column-wise
sum_1=tf.reduce_sum(mat,axis=1)

#sum_0,sum_1
sum_0.numpy(),sum_1.numpy()

(array([99, 65, 49], dtype=int32), array([ 48, 165], dtype=int32))

In [ ]:
mean = tf.reduce_mean(mat)
mean

<tf.Tensor: shape=(), dtype=int32, numpy=35>

In [ ]:
#Find the mean along the axis

#Find the mean row wise
mean_0=tf.reduce_mean(mat,axis=0)
#Find the mean column wise
mean_1=tf.reduce_mean(mat,axis=1)

#mean_0,mean_1
mean_0.numpy(),mean_1.numpy()

(array([49, 32, 24], dtype=int32), array([16, 55], dtype=int32))

In [ ]:
#Find the variance of a tensor
import tensorflow_probability as tfp
variance=tfp.stats.variance(mat)
variance

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1190,  156,  132], dtype=int32)>

In [ ]:
#Dot Product W*X
w=tf.constant([1,2,3])
x=tf.constant([4,5,6])
w,x

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6], dtype=int32)>)

In [ ]:
dot_prod=tf.reduce_sum(tf.multiply(w,x))
dot_prod

<tf.Tensor: shape=(), dtype=int32, numpy=32>

In [ ]:
dot_product=tf.tensordot(w,x,axes=1)
dot_product

<tf.Tensor: shape=(), dtype=int32, numpy=32>

In [ ]:
#Square root of a tensor
z=tf.constant([16.0,25.0,36.0])
z

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([16., 25., 36.], dtype=float32)>

In [ ]:
Sqrt=tf.sqrt(z)
Sqrt

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([4., 5., 6.], dtype=float32)>

# Matrix Multiplication

In [ ]:
# Create a matrix Tensor
matrix1 =tf.constant([[1,2,3],[4,5,6],[11,12,45]])
matrix2 =tf.constant([[7,8],[9,10],[23,43]])
matrix3=tf.constant([[10,20,30],[33,42,87]])
matrix1,matrix2,matrix3

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 1,  2,  3],
        [ 4,  5,  6],
        [11, 12, 45]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [23, 43]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[10, 20, 30],
        [33, 42, 87]], dtype=int32)>)

In [ ]:
matrix1.numpy()

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 45]], dtype=int32)

In [ ]:
matmul1_2=tf.matmul(matrix1,matrix2)
matmul1_2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[  94,  157],
       [ 211,  340],
       [1220, 2143]], dtype=int32)>

In [ ]:
#shortcut operator for multiplication
matrix1 @ matrix2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[  94,  157],
       [ 211,  340],
       [1220, 2143]], dtype=int32)>

In [ ]:
#python matrix multiplication of matrices with different shapes
matrix1 * matrix3

InvalidArgumentError: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [3,3] vs. [2,3] [Op:Mul] name: 

In [ ]:
#python performs elementwise mulitiplication for that both matrix should be of same shape
matrix1 * matrix1


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[   1,    4,    9],
       [  16,   25,   36],
       [ 121,  144, 2025]], dtype=int32)>

In [ ]:
#Matrix multiplication with different inner dimensions
matmul1_3=tf.matmul(matrix1,matrix3)
matmul1_3

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,3], In[1]: [2,3] [Op:MatMul] name: 

In [ ]:
matrix1.shape,matrix3.shape

(TensorShape([3, 3]), TensorShape([2, 3]))

In [ ]:
matrix3_reshape=tf.reshape(matrix3,shape=(3,2))
matrix3_reshape

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 33],
       [42, 87]], dtype=int32)>

In [ ]:
tf.matmul(matrix1,matrix3_reshape)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 196,  347],
       [ 442,  767],
       [2360, 4531]], dtype=int32)>

In [ ]:
tf.reshape(matrix3,shape=(4,2))

InvalidArgumentError: {{function_node __wrapped__Reshape_device_/job:localhost/replica:0/task:0/device:CPU:0}} Input to reshape is a tensor with 6 values, but the requested shape has 8 [Op:Reshape]

#Matrix Transpose

In [ ]:
matrix3

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 20, 30],
       [33, 42, 87]], dtype=int32)>

In [ ]:
#number of rows
matrix3.shape[0]

#number of columns
matrix3.shape[1]

3

In [ ]:
matrix3_transpose=tf.transpose(matrix3)
matrix3_transpose

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 33],
       [20, 42],
       [30, 87]], dtype=int32)>

In [ ]:
tf.matmul(matrix1,matrix3_transpose)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 140,  378],
       [ 320,  864],
       [1700, 4782]], dtype=int32)>

# Create 0's and 1's matrix tensor

In [ ]:
zeros=tf.zeros(shape=(5,5))
zeros

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
zeros.shape[1]

5

In [ ]:
tf.zeros_like(matrix1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [ ]:
ones=tf.ones(shape=(5,5))
ones

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.ones_like(matrix1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)>

# Create an identity matrix tensor: tf.eye()

In [ ]:
identity=tf.eye(5,dtype=tf.int32)
identity

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int32)>

#Concatenate Two Tensors: tf.concat()

In [ ]:
matrix1=[[3,4,6],[7,7,7]]
matrix2=[[1,2,3],[4,5,6]]
matrix1,matrix2

([[3, 4, 6], [7, 7, 7]], [[1, 2, 3], [4, 5, 6]])

In [ ]:
#Concatenation of 2 matrix rowwise
tf.concat([matrix1,matrix2],axis=0)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[3, 4, 6],
       [7, 7, 7],
       [1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
#concatenation of two matrices column-wise
tf.concat([matrix1,matrix2],axis=1)

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[3, 4, 6, 1, 2, 3],
       [7, 7, 7, 4, 5, 6]], dtype=int32)>

# Stack Tensors using tf.stack()

In [ ]:
#stack row-wise
tf.stack([matrix1,matrix2],axis=0)

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[3, 4, 6],
        [7, 7, 7]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

In [ ]:
tf.stack([matrix1,matrix2],axis=0).ndim

3

In [ ]:
#stacking 2 matrix tensors column-wise
tf.stack([matrix1,matrix2],axis=1)

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[3, 4, 6],
        [1, 2, 3]],

       [[7, 7, 7],
        [4, 5, 6]]], dtype=int32)>

In [ ]:
tf.stack([matrix1,matrix2],axis=1).ndim

3